### ISSUE TITLE
chown: invalid spec: 'redmine:' when i start the container

### ISSUE THREAD

**Issue by jackyouyang** [bitnami/bitnami-docker-redmine#103]
logs:
```
Recreating redmine_mariadb_1 ... done
Recreating redmine_application_1 ... done
Attaching to redmine_mariadb_1, redmine_application_1
mariadb_1      | 
mariadb_1      | Welcome to the Bitnami mariadb container
mariadb_1      | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1      | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1      | 
mariadb_1      | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
application_1  | start postfix
application_1  | Starting Postfix Mail Transport Agent: postfix.
application_1  | start rsyslog
application_1  | Starting enhanced syslogd: rsyslogd.
application_1  | 
application_1  | Welcome to the Bitnami redmine container
application_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
application_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
application_1  | 
application_1  | chown: invalid spec: 'redmine:'
redmine_application_1 exited with code 1
mariadb_1      | nami    INFO  Initializing mariadb
mariadb_1      | mariadb INFO 
mariadb_1      | mariadb INFO  ########################################################################
mariadb_1      | mariadb INFO   Installation parameters for mariadb:
mariadb_1      | mariadb INFO     Persisted data and properties have been restored.
mariadb_1      | mariadb INFO     Any input specified will not take effect.
mariadb_1      | mariadb INFO   This installation requires no credentials.
mariadb_1      | mariadb INFO  ########################################################################
mariadb_1      | mariadb INFO 
mariadb_1      | nami    INFO  mariadb successfully initialized
mariadb_1      | INFO  ==> Starting mariadb... 
mariadb_1      | INFO  ==> Starting mysqld_safe...
mariadb_1      | 180706 09:56:14 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1      | 180706 09:56:14 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
```

docker-compose.yml:
```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/data/var/opt/redmine/mariadb_data:/bitnami/mariadb'
  application:
    image: 'mpjoy/redmine:v1'
    ports:
      - '3000:3000'
    volumes:
      - '/data/var/opt/redmine/redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
```
