### ISSUE TITLE
SMTP_TLS setting

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-redmine#108]
I have this in my docker-compose.yml:

```
services:
  redmine:
    image: bitnami/redmine:latest
    environment:
      - SMTP_HOST=my.host.tld
      - SMTP_PORT=587
      - SMTP_USER=sender@my.host.tld
      - SMTP_PASSWORD=somePwd123
      - SMTP_TLS=true
```

and get "535 5.7.8 Error: authentication failed: Invalid authentication mechanism" in redmine when trying to test email notifications. Same user/pw/host works when I test it with swaks from my machine here, using TLS.

postfix on the smarthost tells me:

```
Anonymous TLS connection established
warning: unknown[192.168.16.2]: SASL LOGIN authentication failed: Invalid authentication mechanism
```
So maybe redmine uses some non-allowed auth mechanism here?
Pls advise how to proceed and if I maybe define some parameter in a wrong way.

**Comment by andresbono** [comment]
Hi @stefangweichinger, we can't reproduce your issue. We tried with a similar configuration (using Gmail SMTP) with the following environment variables in the docker-compose file:

```yaml
  redmine:
    image: 'bitnami/redmine:4'
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=someuser@gmail.com
      - SMTP_PASSWORD=somepassword
      - SMTP_TLS=true
```

It sends the mails as expected.

What is the value of the `email_delivery` section in the `/opt/bitnami/redmine/config/configuration.yml` file? Please remember to not expose the user, domain or password.

**Comment by stefangweichinger** [comment]
I checked that section and found that it contains a wrong/older email adress for the SMTP_USER.
I had that one wrong yesterday and thought it would bew overwritten etc
OK, edited that value now and ran docker-compose down (I still have to learn if to use "start/stop" or "down/up" here) ... now the value is correct in the running container.

->

```
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: my.tld
      port: 587
      domain: example.net
      authentication: :login
      user_name: sender@my.tld
      password: somepass
```

That "example.net" is really there, I only edited my.tld to hide my domain.

postfix says "warning: unknown[192.168.32.2]: SASL LOGIN authentication failed: Invalid authentication mechanism"

So I think that redmine should use "PLAIN" instead or something like that.
My postfix is configured quite restrictive ;)
thanks
