### ISSUE TITLE
Error executing 'postInstallation: ELOOP: too many symbolic links encountered, lstat /opt/bitnami/redmine/conf/database.yml'

### ISSUE THREAD

**Issue by ToniDS** [bitnami/bitnami-docker-redmine#113]
**Description**

After restarting my server, I cannot get redmine to work anymore. I have a reverse proxy in my host, which worked perfectly before. Now, the first error I received was that passenger could not bind on port 3000 anymore, as port 3000 is already in use. I then tried updating the images (with docker pull), and now, I get the error described abpve. Postgresql shows: database system is ready to accept connections, but redmine doesn't come up. 

**Steps to reproduce the issue:**

1. Restart server 
2. automatic restart
3. docker-compose -f docker-compose-postgresql.yml up

**Describe the results you received:**

Error: Error executing 'postInstallation: ELOOP: too many symbolic links encountered, lstat /opt/bitnami/redmine/conf/database.yml'

**Describe the results you expected:**
Running postgresql and redmine container, accessible via port 3000 on loopback

**Additional information you deem important (e.g. issue happens only occasionally):**

This is my docker compose: 
```

version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_data:/bitnami'
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '127.0.0.1:1025:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgresql
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local
  redmine_data:
    driver: local
```

I had restart: always on here for both containers. 

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.1-ce
 API version:       1.39
 Go version:        go1.11.4
 Git commit:        4c52b901c6
 Built:             Thu Jan 10 06:51:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       4c52b901c6
  Built:            Thu Jan 10 06:50:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 7
Server Version: 18.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b.m
runc version: 079817cc26ec5292ac375bb9f47f373d33574949
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.20.6-arch1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.79GiB
Name: arch.rlwinm.de
ID: OFDO:Y44N:43SE:CJOP:3QXZ:7JOP:BAHF:2MBC:4WTW:NRO3:7U2E:6W72
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build unknown
docker-py version: 3.7.0
CPython version: 3.7.2
OpenSSL version: OpenSSL 1.1.1a  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Host: arch
