### ISSUE TITLE
I can't connect to external MySQL DB in other server

### ISSUE THREAD

**Issue by vmansur** [bitnami/bitnami-docker-redmine#117]
**Description**
I can't connect to external MySQL DB in other server

**Steps to reproduce the issue:**

docker-compose.yaml:
```
version: '2'
services:
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '80:3000'
    environment:
      - REDMINE_PASSWORD=password
      - REDMINE_USER=user
      - REDMINE_DB_USERNAME=db_user
      - REDMINE_DB_PASSWORD=db_password
      - REDMINE_DB_MYSQL=x.x.x.x
      - REDMINE_DB_PORT_NUMBER=3306
    volumes:
      - 'redmine_data:/bitnami'
volumes:
  redmine_data:
    driver: local
```
run:
` docker-compose up`

**Describe the results you received:**
```
redmine_1  | 
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | 
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | redmine INFO  Redmine has been already initialized, restoring...
redmine_1  | mysql-c INFO  Trying to connect to MySQL server
```
for a really long time...
after a while:
```
redmine_1  | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
docker3_redmine_1 exited with code 1

```

**Describe the results you expected:**

Connection sucessfull on the database and redmine running as expected

**Additional information you deem important (e.g. issue happens only occasionally):**
It Looks like the environment variables are not working as expected 

I am sure that the MySQL server is working with this user and password. 
`mysql -h <host> -u <user> -p 
`
works normally

Using Docker on AWS Linux AMI 2 
Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
docker-compose version 1.24.0-rc1, build 0f3d4dda

- Output of `docker info`:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.104-95.84.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.794GiB
Name: xxxxxx
ID: Y23I:5W72:S3UK:P72R:KNWI:ZPRX:TO6D:2LCO:C2SZ:WIEE:UZKM:Z6ZA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
uname -a
`Linux ip-xxxxxx 4.14.104-95.84.amzn2.x86_64 #1 SMP Sat Mar 2 00:40:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
