### ISSUE TITLE
REDMINE_DB_PORT_NUMBER not work

### ISSUE THREAD

**Issue by iampastor** [bitnami/bitnami-docker-redmine#128]
**Description**

when i set REDMINE_DB_PORT_NUMBER to other number, there is no effect on redmine, it still connect to 3306.

**Steps to reproduce the issue:**

1. set REDMINE_DB_PORT_NUMBER=6006
2. docker-compose up -d

**Describe the results you received:**
```
production:
  adapter: mysql2
  database: bitnami_redmine
  host: mariadb
  username: bn_redmine
  password:
  encoding: utf8

development:
  adapter: mysql2
  database: bitnami_redmine_development
  host: mariadb
  username: bn_redmine
  password:
  encoding: utf8
```

**Describe the results you expected:**

should be port config in config file

```
production:
  adapter: mysql2
  database: bitnami_redmine
  host: mariadb
  port: 6006
  username: bn_redmine
  password:
  encoding: utf8

development:
  adapter: mysql2
  database: bitnami_redmine_development
  host: mariadb
  port: 6006
  username: bn_redmine
  password:
  encoding: utf8
```
**Additional information you deem important (e.g. issue happens only occasionally):**
this is netstat output:
```
root@5c7ad274207c:/# netstat -tpn
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 172.20.0.3:3000         172.20.0.1:53620        ESTABLISHED -
tcp        0      0 172.20.0.3:47422        172.20.0.2:3306         ESTABLISHED -
tcp        0      0 127.0.0.1:3000          127.0.0.1:51988         ESTABLISHED -
tcp        0      0 172.20.0.3:3000         172.20.0.1:53622        ESTABLISHED -
tcp        0      0 127.0.0.1:3000          127.0.0.1:51986         TIME_WAIT   -
tcp        0      0 127.0.0.1:51988         127.0.0.1:3000          ESTABLISHED -
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 36
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: QMJF:KP5H:GPDK:2JM4:PHOR:AV46:OSBG:26SS:ZRIG:3ETD:GXQ2:EGV6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 51
 Goroutines: 76
 System Time: 2019-09-06T09:03:58.9100705Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://24cffjw6.mirror.aliyuncs.com/
 http://c4727f7f.m.daocloud.io/
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
