### ISSUE TITLE
Failed to start with err: "Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'"

### ISSUE THREAD

**Issue by gainskills** [bitnami/bitnami-docker-redmine#136]
**Description**
The docker instance failed to boot up due to error: 
`Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'`

**Steps to reproduce the issue:**

1. The docker-compose file:

```
version: '3.7'

services:

  redmine:
    image: bitnami/redmine:4.1.0-debian-9-r0
    restart: always
    ports:
      - 80:3000
    volumes:
      - redmine_data:/bitnami
    environment:
      - REDMINE_PLUGINS_MIGRATE=1
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=postgres
      - REDMINE_DB_PASSWORD=posgrestestpwd

      - REDMINE_DB_NAME=postgres
      - REDMINE_DB_PORT_NUMBER=5432
      - REDMINE_USERNAME=testusr
      - REDMINE_PASSWORD=testpwd
      - REDMINE_LANGUAGE=en
      - SMTP_HOST=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_USER=test@test.com
      - SMTP_PASSWORD=testpwd

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'posgrestestpwd'

volumes:
  redmine_data:
    driver: local
  postgres_data:
    driver: local
```

2. start the instance with the command: 'docker-compose up'

**Describe the results you received:**

```
redmine_1  | 
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | 
db_1       | 2019-12-23 20:13:02.978 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
db_1       | 2019-12-23 20:13:02.978 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2019-12-23 20:13:02.978 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1       | 2019-12-23 20:13:02.982 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2019-12-23 20:13:02.993 UTC [18] LOG:  database system was interrupted; last known up at 2019-12-23 20:08:53 UTC
db_1       | 2019-12-23 20:13:03.182 UTC [18] LOG:  database system was not properly shut down; automatic recovery in progress
db_1       | 2019-12-23 20:13:03.184 UTC [18] LOG:  redo starts at 0/2557688
db_1       | 2019-12-23 20:13:03.184 UTC [18] LOG:  invalid record length at 0/25576C0: wanted 24, got 0
db_1       | 2019-12-23 20:13:03.184 UTC [18] LOG:  redo done at 0/2557688
db_1       | 2019-12-23 20:13:03.193 UTC [1] LOG:  database system is ready to accept connections
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'
```

**Describe the results you expected:**

The instance should be boot up.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 22
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.855GiB
 Name: docker-desktop
 ID: PKGO:RXCD:VB7I:WS6Q:CSQJ:2NYQ:4TLM:6MGC:KMWQ:V57H:24Q5:TWYO
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 31
  Goroutines: 47
  System Time: 2019-12-23T20:22:01.6462867Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by sameersbn** [comment]
@gainskills The values of `REDMINE_DB_PASSWORD` and `POSTGRES_PASSWORD` do not match in the `docker-compose.yaml` file.  Please correct it and try again:

```bash
docker-compose down -v # also removes existing volumes 
docker-compose up
```

**Comment by gainskills** [comment]
> @gainskills The values of `REDMINE_DB_PASSWORD` and `POSTGRES_PASSWORD` do not match in the `docker-compose.yaml` file. Please correct it and try again:
> 
> ```shell
> docker-compose down -v # also removes existing volumes 
> docker-compose up
> ```

Thanks a lot for pointing this out. Actually, the issue is still there because the inconsistent didn't in my real environment. It's from my mistake when I submitting this issue and removing my real password.

BTW, Merry Christmas.

**Comment by sameersbn** [comment]
@gainskills Merry Christmas :santa: 

I saw the same issue, until I fixed the password problem.

```yaml
version: '3.7'

services:

  redmine:
    image: bitnami/redmine:4.1.0-debian-9-r0
    restart: always
    ports:
      - 80:3000
    volumes:
      - redmine_data:/bitnami
    environment:
      - REDMINE_PLUGINS_MIGRATE=1
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=postgres
      - REDMINE_DB_PASSWORD=protempobsdbpwd

      - REDMINE_DB_NAME=postgres
      - REDMINE_DB_PORT_NUMBER=5432
      - REDMINE_USERNAME=testusr
      - REDMINE_PASSWORD=testpwd
      - REDMINE_LANGUAGE=en
      - SMTP_HOST=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_USER=test@test.com
      - SMTP_PASSWORD=testpwd

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'protempobsdbpwd'

volumes:
  redmine_data:
    driver: local
  postgres_data:
    driver: local
```

```bash
$ docker-compose up
Creating network "test_default" with the default driver
Creating volume "test_redmine_data" with local driver
Creating volume "test_postgres_data" with local driver
Creating test_redmine_1 ... done
Creating test_db_1      ... done
Attaching to test_db_1, test_redmine_1
db_1       | The files belonging to this database system will be owned by user "postgres".
db_1       | This user must also own the server process.
db_1       | 
db_1       | The database cluster will be initialized with locale "en_US.utf8".
db_1       | The default database encoding has accordingly been set to "UTF8".
db_1       | The default text search configuration will be set to "english".
db_1       | 
db_1       | Data page checksums are disabled.
redmine_1  | 
redmine_1  | Welcome to the Bitnami redmine container
db_1       | 
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
db_1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
redmine_1  | 
db_1       | creating subdirectories ... ok
db_1       | selecting dynamic shared memory implementation ... posix
db_1       | selecting default max_connections ... 100
db_1       | selecting default shared_buffers ... 128MB
db_1       | selecting default time zone ... UTC
db_1       | creating configuration files ... ok
db_1       | running bootstrap script ... ok
db_1       | performing post-bootstrap initialization ... sh: locale: not found
db_1       | 2019-12-24 05:12:22.349 UTC [28] WARNING:  no usable system locales were found
db_1       | ok
db_1       | syncing data to disk ... ok
db_1       | 
db_1       | 
db_1       | Success. You can now start the database server using:
db_1       | 
db_1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1       | 
db_1       | initdb: warning: enabling "trust" authentication for local connections
db_1       | You can change this by editing pg_hba.conf or using the option -A, or
db_1       | --auth-local and --auth-host, the next time you run initdb.
db_1       | waiting for server to start....2019-12-24 05:12:22.726 UTC [33] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
db_1       | 2019-12-24 05:12:22.731 UTC [33] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2019-12-24 05:12:22.760 UTC [34] LOG:  database system was shut down at 2019-12-24 05:12:22 UTC
db_1       | 2019-12-24 05:12:22.765 UTC [33] LOG:  database system is ready to accept connections
db_1       |  done
db_1       | server started
db_1       | 
db_1       | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1       | 
db_1       | waiting for server to shut down....2019-12-24 05:12:22.816 UTC [33] LOG:  received fast shutdown request
db_1       | 2019-12-24 05:12:22.821 UTC [33] LOG:  aborting any active transactions
db_1       | 2019-12-24 05:12:22.821 UTC [33] LOG:  background worker "logical replication launcher" (PID 40) exited with exit code 1
db_1       | 2019-12-24 05:12:22.821 UTC [35] LOG:  shutting down
db_1       | 2019-12-24 05:12:22.853 UTC [33] LOG:  database system is shut down
db_1       |  done
db_1       | server stopped
db_1       | 
db_1       | PostgreSQL init process complete; ready for start up.
db_1       | 
db_1       | 2019-12-24 05:12:22.925 UTC [1] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
db_1       | 2019-12-24 05:12:22.925 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2019-12-24 05:12:22.925 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1       | 2019-12-24 05:12:22.943 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2019-12-24 05:12:22.979 UTC [42] LOG:  database system was shut down at 2019-12-24 05:12:22 UTC
db_1       | 2019-12-24 05:12:22.986 UTC [1] LOG:  database system is ready to accept connections
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | redmine INFO  Configuring Redmine database...
redmine_1  | postgre INFO  Trying to connect to PostgreSQL server
redmine_1  | postgre INFO  Found PostgreSQL server listening at db:5432
redmine_1  | postgre INFO  PostgreSQL server listening and working at db:5432
redmine_1  | redmine INFO  Preparing Redmine environment...
redmine_1  | redmine INFO  Generating new secret...
redmine_1  | redmine INFO  Migrating database...
...
```
