### ISSUE TITLE
docker stack deploy failing

### ISSUE THREAD

**Issue by jonfen** [bitnami/bitnami-docker-redmine#138]
**Description**

**Steps to reproduce the issue:**

1. Create directories on city-dockerstaging: /srv/redmine/mariadb and /srv/redmine/redmine.  Create file: /srv/redmine/docker-compose.yml 
```
version: '3.7'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      - '/srv/redmine/mariadb:/bitnami/mariadb'
  redmine:
    image: 'bitnami/redmine:4'
    environment:
      # https://github.com/bitnami/bitnami-docker-redmine#environment-variables
      # Redmine application username. Default: user
      - REDMINE_USERNAME=user  
      # Redmine application password. Default: bitnami1
      - REDMINE_PASSWORD=bitnami1
      # Redmine application email. Default: user@example.com
      - REDMINE_EMAIL=user@example.com
      # Redmine application default language. Default: en
      - REDMINE_LANGUAGE=en
      # Database user the application will connect with. Default: bn_redmine
      - REDMINE_DB_USERNAME=bn_redmine
      # Password for the database user.
      # - REDMINE_DB_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
      # Database the application will connect to. Default: bitnami_redmine
      - REDMINE_DB_NAME=bitnami_redmine
      # Hostname for MySQL server. Default: mariadb
      - REDMINE_DB_MYSQL=mariadb
      # Hostname for PostgreSQL server. No defaults
      # - REDMINE_DB_POSTGRES=
      # Port used by database server. Default: 3306
      - REDMINE_DB_PORT_NUMBER=3306
    
      # https://github.com/bitnami/bitnami-docker-redmine#smtp-configuration
      - SMTP_HOST=dc-city2
      - SMTP_PORT=25
      - SMTP_USER=user@example.com
      - SMTP_PASSWORD=none
      # Use TLS encription with SMTP. Default true
      - SMTP_TLS=false
    ports:
      - '9090:3000'
    volumes:
      - '/srv/redmine/redmine:/bitnami'
    depends_on:
      - mariadb
```
2.
```
ssh city-dockerstaging docker stack deploy -c /srv/redmine/docker-compose.yml redmine
```

**Describe the results you received:**
`docker service ls`
```
ycgtj33h3emr        redmine_mariadb           replicated          0/1                 bitnami/mariadb:10.3
s0024de6j20f        redmine_redmine           replicated          1/1                 bitnami/redmine:4                                              *:9090->3000/tcp
```
`journalctl -fu docker.service`
```
Jan 20 16:04:19 city-dockerstaging dockerd[1452]: time="2020-01-20T16:04:19.716218600Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jan 20 16:04:20 city-dockerstaging dockerd[1452]: time="2020-01-20T16:04:20.010701801Z" level=warning msg="fcb2997e696ccbd1a175ce9adb5cc2f0f9a48a7f01d45ddeabacdf92607a2a27 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/fcb2997e696ccbd1a175ce9adb5cc2f0f9a48a7f01d45ddeabacdf92607a2a27/mounts/shm, flags: 0x2: no such file or directory"
Jan 20 16:04:20 city-city-dockerstaging dockerd[1452]: time="2020-01-20T16:04:20.164808411Z" level=error msg="fatal task error" error="task: non-zero exit (1)" module=node/agent/taskmanager node.id=udjre1tk5h7qr9c8wtdyu6fwz service.id=ycgtj33h3emr0m3iz18wvg0tf task.id=uc46hrvn4asfhbhe6riqaom0b

```

**Describe the results you expected:**

I was hoping that the bitnami image supported docker stack deploy like the redmine.org image: 
https://hub.docker.com/_/redmine/

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`: 

```
Docker version 19.03.5, build 633a0ea838
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 38
  Running: 15
  Paused: 0
  Stopped: 23
 Images: 44
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: udjre1tk5h7qr9c8wtdyu6fwz
  Is Manager: true
  ClusterID: zavsopjd8ludbx13hfa4ktn5q
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.111.128.70
  Manager Addresses:
   10.111.128.70:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-72-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 22.96GiB
 Name: city-dockerstaging
 ID: G35Z:5JEP:TV6J:5R4W:ECF3:N2QB:UOF6:SLXP:UYBD:I3FD:2SQ7:VT4Y
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
N/A, we are using docker swarm, not docker-compose.
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
