### ISSUE TITLE
Connect Redmine container to external MySQL server

### ISSUE THREAD

**Issue by bertalanimre** [bitnami/bitnami-docker-redmine#139]
**Description**

I already have an installed instance of Redmine 4 with an external MySQL server it connects to, that needs to be moved to another server. On the new server, I don't want to take time to install Ruby and everything else for it, so I though I can install simply the docker version, attach my original files folder and connect it to the external MySQL server too. The 2nd part is simply not working, it is not described at all, how to achieve it.
Similar question was [issue 117](https://github.com/bitnami/bitnami-docker-redmine/issues/117), but that is discontinued and closed

Environment on the new server:
* CentOS 7
* MySQL 5.7
* NginX 1.16.1 (Will not use, it just causes small issues because of serving web traffic to the container)
* docker-compose version 1.23.2, build 1110ad01
* Docker version 19.03.4, build 9013bf583a

Can we have an updated README or a solution for this thread? What variables are need to be set to tell Redmine, there is a different database server?

```
version: '2'
services:
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '8080:3000'
    environment:
      - REDMINE_PASSWORD=password
      - REDMINE_USER=user
      - REDMINE_DB_USERNAME=secretuser
      - REDMINE_DB_PASSWORD=secretpassword
      - REDMINE_DB_MYSQL=x.x.x.x
      - REDMINE_DB_PORT_NUMBER=3306
    volumes:
      - 'redmine_data:/bitnami'
volumes:
  redmine_data:
    driver: local

```
**Proof of reachable DB**

If I start the container with *docker-compose up* and then enter the "non working" container via bash and try to connect to my external database manually *mysql -u root -p -h x.x.x.x* it works like a charm.

**Comment by bertalanimre** [comment]
Updated title to be more specific

**Comment by bertalanimre** [comment]
Updated my YAML file with adding ` - REDMINE_DB_MYSQL=x.x.x.x` but when I start composer up, I can see that it STILL tries to connect to mariadb.

```
redmine_1  | mysql-c INFO  Trying to connect to MySQL server
redmine_1  | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
redmine4_redmine_1 exited with code 1
```
How? Why? From where?

**Comment by jotamartos** [comment]
Hi @bertalanimre ,

I just verified that the first run of the container works fine when specifying a database IP. I used the docker-compose.yml information you shared and I also modified the docker-compose.yml file to use different parameters and everything worked as expected.  

```
version: '2'
  redmine:
    image: 'bitnami/redmine:4'
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_PASSWORD=bitnami
      - REDMINE_DB_NAME=bitnami_redmine
      - REDMINE_DB_MYSQL=IP_HERE
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami'
volumes:
  redmine_data:
    driver: local
```

This was the output of the docker-compose up command 

```
redmine_1  |
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | Send us your feedback at containers@bitnami.com
redmine_1  |
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | redmine INFO  Configuring Redmine database...
redmine_1  | mysql-c INFO  Trying to connect to MySQL server
redmine_1  | mysql-c INFO  Found MySQL server listening at IP_HERE:3306
redmine_1  | mysql-c INFO  MySQL server listening and working at IP_HERE:3306
redmine_1  | redmine INFO  Preparing Redmine environment...
redmine_1  | redmine INFO  Generating new secret...
redmine_1  | redmine INFO  Migrating database...
```

I'm going to check now how the container behaves when attaching the redmine files to the container. I'll update this ticket once I have more information.
