### ISSUE TITLE
Post installation script requires a full configuration for SMTP, not allowing partial

### ISSUE THREAD

**Issue by PYL666** [bitnami/bitnami-docker-redmine#147]
**Description**

When configuring STMP in docker-compose.yml file, I set the SMTP configuration like this:

`- SMTP_HOST=smtp.example.com`

Then postInstallation script fails telling me:

```
redmine_1  | Error executing 'postInstallation': You should specify username, password, host, port for SMTP configuration
local_redmine_1 exited with code 1
```

**Steps to reproduce the issue:**

1. Edit stock `docker-compose.yml` file with a mostly empty SMTP configuration (only host, no user, no password, etc.)
2. Launch: `docker-compose up`

**Describe the results you received:**
Launch of redmine container fails with message:

```
redmine_1  | redmine INFO  Preparing Redmine environment...
redmine_1  | Error executing 'postInstallation': You should specify username, password, host, port for SMTP configuration
local_redmine_1 exited with code 1

```
**Describe the results you expected:**

A working redmine site with a configuration with my smtp host configure but with no user and no password.

**Additional information you deem important (e.g. issue happens only occasionally):**

Setting the variable empty fails too:
```
      - SMTP_TLS=false
      - SMTP_PORT=25
      - SMTP_USER=
      - SMTP_PASSWORD=
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.778GiB
 Name: docker-desktop
 ID: XBJN:CLU7:5EYN:DIDV:EKB7:TY5A:CKQD:DIV6:LO43:KDV6:X2TC:FD62
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 37
  Goroutines: 66
  System Time: 2020-03-20T16:06:03.164275598Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

On Mac OS X:
Docker desktop: version 2.2.0.4 (43472)
Channel stable

**Comment by andresbono** [comment]
Hi @PYL666, The container doesn't support unauthenticated SMTP connections. Have you tried by specifying dummy values for the username and password? How is your SMTP server responding?

**Comment by scristalli** [comment]
Hi @andresbono, I confirm the issue. I'm using the stable Helm chart for Kubernetes, which uses this container. In my case, dummy values result in the SMTP server complaining with `503 5.5.1 Error: authentication not enabled`.
Would it be possible not to apply any logic and simply map the values to Redmine's configuration, since the software allows for non-authenticated SMTP?

**Comment by PYL666** [comment]
@andresbono : I did make the test. The thing is that I have no control on my SMTP server.
I am actually making a migration of an existing Redmine towards a Docker based image.
Formerly, the SMTP configuration was:

```
    smtp_settings:
      address: smtp.example.com 
      port: 25
      domain: example.com
      authentication: :none
      user_name: 
      password: 
```

And I need to replicate this configuration anyway...

**Comment by PYL666** [comment]
Just thinking about the issue, it appears that it was caused by over-development: why write code to check against a case that is otherwise valid ? Perhaps simply a warning could have been acceptable.

**Comment by andresbono** [comment]
It sounds reasonable. We will work on removing the validation as it is not necessary for all the cases.

**Comment by PYL666** [comment]
@andresbono : Thank you to consider my request.

**Comment by beltran-rubo** [comment]
Hi @PYL666, we just released a new Redmine version 4.1.0-debian-10-r43 that fixes this issue. Could you please try again and confirm it works for you? thanks

**Comment by PYL666** [comment]
Hi @beltran-rubo,

I did not test `r43` but `latest`.
I do not think it is correct because from variable configuration:
```
- SMTP_HOST=smtp.mydomain.net
- SMTP_TLS=false
- SMTP_PORT=25
- SMTP_USER=
- SMTP_PASSWORD=
```
I was expecting:
```
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.mydomain.net 
      port: 25
      domain: mydomain.net
      authentication: :none
      user_name:
      password:
```
but I got:
```
  email_delivery: 
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.mydomain.net
      port: 25
      domain: example.net
      authentication: :login
      user_name:
      password:
```
Please note the:

- `enable_starttls_auto: true` (instead of `   `)
- `authentication: :login` (instead of `authentication: :none`)
- ... and the funny `domain: example.net` (instead of `domain: mydomain.net`)

**Comment by PYL666** [comment]
Further tests give same incorrect result with:
```
- SMTP_HOST=smtp.mydomain.net
- SMTP_PORT=25
```
or
```
- SMTP_HOST=smtp.mydomain.net
- SMTP_PORT=25
- SMTP_TLS=false
```
And just
```
- SMTP_HOST=smtp.mydomain.net
```
fails because it complains about port number (while it could default to 25 when none is supplied).

**Comment by PYL666** [comment]
... and finally, I redid tests with r43 with same outcomes (not surprisingly, I'll assume).

**Comment by beltran-rubo** [comment]
Hi @PYL666,

We have been working on removing the validation to support empty user/pass but we do not change the logic for the auth, TLS or the domain. We will look into this.

**Comment by PYL666** [comment]
@beltran-rubo : Thank you for you prompt and continuous support.

**Comment by beltran-rubo** [comment]
Hi @PYL666 

We released a new version "4.1.0-debian-10-r54" that contains the new environment variables: SMTP_AUTHENTICATION and SMTP_DOMAIN. There is more info the README file E.g. setting the env vars below you got the following section in the config file:

```
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=25
      - SMTP_TLS=false
      - SMTP_AUTHENTICATION=none
      - SMTP_DOMAIN=mydomain.com
```

```
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: false
      address: smtp.example.com
      port: 25
      domain: mydomain.com
      authentication: :none
      user_name: 
      password: 
```

Please confirm that fixes your issue.

**Comment by PYL666** [comment]
@beltran-rubo : Thank you. Looks good. I'll be testing that.

**Comment by PYL666** [comment]
Hello @beltran-rubo,

I have tested `r54` and used this configuration isn `docker-compose.yml`:
```
      - SMTP_HOST= smtp.example.com
      - SMTP_PORT=25
      - SMTP_TLS=false
      - SMTP_AUTHENTICATION=none
      - SMTP_DOMAIN= example.com
```
and got:
```
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: false
      address: smtp.example.com
      port: 25
      domain: example.com
      authentication: :none
      user_name: 
      password: 
```
while expecting:
```
  email_delivery:
    delivery_method: :smtp
    smtp_settings:      
      address: smtp.example.com 
      port: 25
      domain: example.com
      authentication: :none
      user_name: 
      password: 
```
I believe this is close enough for my use case but I cannot test it fully at this time.
When my integration is finished, I'll post the actual outcome here.
But I believe the issue is fixed at this time.

Thank you for your support. :smile: 👍
