### ISSUE TITLE
Redmine pod unable to connect to MySQL server

### ISSUE THREAD

**Issue by NitsujY** [bitnami/bitnami-docker-redmine#152]
**Which chart: redmine-14.1.19** 
I am using kubernetes and helm to install the redmine
I used clean install kubernetes with kubeadm/cillium network
The installation always stuck at this point. I have no idea how to continue debugging. I am begging for any help.

**To Reproduce:**
`helm install -g bitnami/redmine --values redmine.values -n redmine`

```
kubectl logs pod/redmine-1591632520-548fd7f7d9-9hpbw -n redmine

Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Redmine has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
```

I can successfully go into the redmine pod in bash shell and use mysql to test the connection to mariadb

```
root@redmine-1591632520-548fd7f7d9-9hpbw:/# env
KUBERNETES_SERVICE_PORT_HTTPS=443
REDMINE_1591632520_MARIADB_PORT_3306_TCP=tcp://10.97.115.2:3306
KUBERNETES_SERVICE_PORT=443
HOSTNAME=redmine-1591632520-548fd7f7d9-9hpbw
REDMINE_1591632520_MARIADB_SERVICE_PORT_MYSQL=3306
REDMINE_DB_USERNAME=bn_redmine
REDMINE_LANG=en
REDMINE_1591632520_PORT_80_TCP_PORT=80
REDMINE_1591632520_PORT_80_TCP=tcp://10.108.125.220:80
PWD=/
OS_FLAVOUR=debian-10
REDMINE_DB_NAME=bitnami_redmine
REDMINE_EMAIL=user@example.com
REDMINE_1591632520_MARIADB_SERVICE_PORT=3306
REDMINE_1591632520_MARIADB_PORT=tcp://10.97.115.2:3306
REDMINE_1591632520_PORT_80_TCP_PROTO=tcp
SMTP_TLS=true
HOME=/root
REDMINE_1591632520_SERVICE_PORT_HTTP_REDMINE=80
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
REDMINE_1591632520_SERVICE_PORT=80
REDMINE_1591632520_MARIADB_PORT_3306_TCP_PROTO=tcp
REDMINE_USERNAME=user
REDMINE_LANGUAGE=en
SMTP_PORT=
REDMINE_DB_PASSWORD=password
REDMINE_1591632520_MARIADB_PORT_3306_TCP_ADDR=10.97.115.2
TERM=xterm
BITNAMI_IMAGE_VERSION=4.1.1-debian-10-r42
SMTP_AUTHENTICATION=login
SMTP_DOMAIN=example.com
SHLVL=1
REDMINE_1591632520_MARIADB_PORT_3306_TCP_PORT=3306
KUBERNETES_PORT_443_TCP_PROTO=tcp
REDMINE_PASSWORD=password
BITNAMI_APP_NAME=redmine
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
SMTP_PASSWORD=
REDMINE_1591632520_MARIADB_SERVICE_HOST=10.97.115.2
SMTP_USER=
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
OS_NAME=linux
PATH=/opt/bitnami/ruby/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/mysql/bin:/opt/bitnami/git/bin:/opt/bitnami/common/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
REDMINE_DB_MYSQL=redmine-1591632520-mariadb
REDMINE_1591632520_PORT=tcp://10.108.125.220:80
REDMINE_DB_PORT_NUMBER=
SMTP_HOST=
REDMINE_DB_POSTGRES=
REDMINE_1591632520_PORT_80_TCP_ADDR=10.108.125.220
REDMINE_1591632520_SERVICE_HOST=10.108.125.220
OS_ARCH=amd64
_=/usr/bin/env
root@redmine-1591632520-548fd7f7d9-9hpbw:/# mysql -u root -h redmine-1591632520-mariadb -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 83
Server version: 10.3.23-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| bitnami_redmine    |
| information_schema |
| mysql              |
| performance_schema |
| test               |
+--------------------+
5 rows in set (0.008 sec)
```

Here is my redmine value used in helm

```
image:
  registry: docker.io
  repository: bitnami/redmine
  tag: 4.1.1-debian-10-r42
  pullPolicy: IfNotPresent
redmineUsername: user
redminePassword: password
redmineEmail: user@example.com
redmineLanguage: en
podDisruptionBudget:
  enabled: false
replicas: 1
resources
  limits: {}
  requests: {}
serviceAccount:
  create: true
securityContext: {}
podAnnotations: {}
affinity: {}
nodeSelector: {}
tolerations: []
livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 500Gi
databaseType: mariadb
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_redmine
    user: bn_redmine
    password: password
  rootUser:
     password: password
  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 100Gi
postgresql:
  enabled: false
  postgresqlDatabase: bitnami_redmine
  postgresqlUsername: bn_redmine
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
externalDatabase:
  host: localhost
  name: database
  user: user
  password: ""
  port: 3306
service:
  type: ClusterIP
  port: 80
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  nodePorts:
    http: ""
  externalTrafficPolicy: Cluster
ingress:
  enabled: false
  certManager: false
  hostname: redmine.local
  tls: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  secrets: []
mailReceiver:
  enabled: false
  schedule: "*/5 * * * *"
  suspend: true
  image:
    registry: docker.io
    repository: bitnami/redmine
    tag: 4.1.1-debian-10-r41
    pullPolicy: IfNotPresent
  mailProtocol: IMAP
  host: ""
  port: 993
  username: ""
  password: ""
  ssl: true
  startTLS: false
  imapFolder: "INBOX"
  moveOnSuccess: ""
  moveOnFailure: ""
  unknownUserAction: ingore
  noPermissionCheck: 0
  noAccountNotice: 1
  defaultGroup: ""
  project: ""
  projectFromSubaddress: ""
  status: ""
  tracker: ""
  category: ""
  priority: ""
  assignedTo: ""
  allowOverride: ""
```

Mariadb can successfully created
```
kubectl describe pod/redmine-1591632520-mariadb-0 -n redmine
Name:         redmine-1591632520-mariadb-0
Namespace:    redmine
Priority:     0
Node:         lab-node1/10.240.0.51
Start Time:   Tue, 09 Jun 2020 00:09:03 +0800
Labels:       app=mariadb
              chart=mariadb-7.4.2
              component=master
              controller-revision-hash=redmine-1591632520-mariadb-5f5fdb4cf
              release=redmine-1591632520
              statefulset.kubernetes.io/pod-name=redmine-1591632520-mariadb-0
Annotations:  <none>
Status:       Running
IP:           10.217.1.37
IPs:
  IP:           10.217.1.37
Controlled By:  StatefulSet/redmine-1591632520-mariadb
Containers:
  mariadb:
    Container ID:   docker://f6f947479420a0af83a2514d211f1f35268e3ac06068595b3d71ee9ad5da6654
    Image:          docker.io/bitnami/mariadb:10.3.23-debian-10-r0
    Image ID:       docker-pullable://bitnami/mariadb@sha256:1cd905988dcefc2cdd39e994b2f4392dd744498fe0d1d5f679f2011868a5047f
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 09 Jun 2020 00:09:26 +0800
    Ready:          True
    Restart Count:  0
    Liveness:       exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [sh -c password_aux="${MARIADB_ROOT_PASSWORD:-}"
if [ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]; then
    password_aux=$(cat $MARIADB_ROOT_PASSWORD_FILE)
fi
mysqladmin status -uroot -p$password_aux
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MARIADB_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'redmine-1591632520-mariadb'>  Optional: false
      MARIADB_USER:           bn_redmine
      MARIADB_PASSWORD:       <set to the key 'mariadb-password' in secret 'redmine-1591632520-mariadb'>  Optional: false
      MARIADB_DATABASE:       bitnami_redmine
    Mounts:
      /bitnami/mariadb from data (rw)
      /opt/bitnami/mariadb/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f5gc6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-redmine-1591632520-mariadb-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      redmine-1591632520-mariadb
    Optional:  false
  default-token-f5gc6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-f5gc6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From                Message
  ----     ------            ----               ----                -------
  Warning  FailedScheduling  17m (x4 over 17m)  default-scheduler   running "VolumeBinding" filter plugin for pod "redmine-1591632520-mariadb-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         17m                default-scheduler   Successfully assigned redmine/redmine-1591632520-mariadb-0 to lab-node1
  Normal   Pulling           17m                kubelet, lab-node1  Pulling image "docker.io/bitnami/mariadb:10.3.23-debian-10-r0"
  Normal   Pulled            17m                kubelet, lab-node1  Successfully pulled image "docker.io/bitnami/mariadb:10.3.23-debian-10-r0"
  Normal   Created           17m                kubelet, lab-node1  Created container mariadb
  Normal   Started           17m                kubelet, lab-node1  Started container mariadb
```

Here is my node and svc

```
kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION
lab-master   Ready    master   22m   v1.18.3
lab-node1    Ready    <none>   21m   v1.18.3
lab-node2    Ready    <none>   21m   v1.18.3

 kubectl get svc -A
NAMESPACE     NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes                   ClusterIP   10.96.0.1        <none>        443/TCP                  23m
kube-system   kube-dns                     ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   23m
redmine       redmine-1591632520           ClusterIP   10.108.125.220   <none>        80/TCP                   19m
redmine       redmine-1591632520-mariadb   ClusterIP   10.97.115.2      <none>        3306/TCP                 19m
```
