### ISSUE TITLE
Error executing 'postInstallation': ENOENT: no such file or directory, stat '/opt/bitnami/redmine/public/themes'

### ISSUE THREAD

**Issue by michafn** [bitnami/bitnami-docker-redmine#153]
I am using an own image based on the bitnami image, since we would like to include themes and plugins properly.
So this is our dockerfile:

```
FROM docker.io/bitnami/redmine:4.1.0-debian-10-r25
RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev
WORKDIR /opt/bitnami/redmine/
COPY plugins/ /opt/bitnami/redmine/plugins
COPY themes/ /opt/bitnami/redmine/public/themes
RUN chown 1001:1001 . -R
#COPY ./redmine_issue_templates/* /opt/bitnami/redmine/redmine_issue_templates/
RUN bundle config unset deployment
RUN bundle install --no-deployment
```
however this results in an error every time i run it:

```
nami    INFO  Initializing redmine
redmine INFO  Configuring Redmine database...
handler WARN  Using /opt/bitnami/redmine as working directory
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at redmine-prod-postgresql:5432
postgre INFO  PostgreSQL server listening and working at redmine-prod-postgresql:5432
redmine INFO  Preparing Redmine environment...
redmine INFO  Generating new secret...
redmine INFO  Migrating database...
Error executing 'postInstallation': ENOENT: no such file or directory, stat '/opt/bitnami/redmine/public/themes'
```
is there anything i am doing wrong?! It seems there is a lot of magic in the bitnami way of doing things, however i don't understand it quite yet. Seems everything is made more complex and quite clumsy to debug. It should be fairly simple (as it was in former times) to add plugins and themes, but apparently there is something happening in the background that I don't understand...

**Comment by michafn** [comment]
also changing to 

```
COPY plugins/ /bitnami/redmine/plugins
COPY themes/ /bitnami/redmine/public/themes

```
since /bitnami/redmine is apparently to expose those folders result sin the same error

**Comment by marcosbc** [comment]
@michafn I couldn't reproduce this issue. I created this folder structure:

```
Dockerfile
/docker-compose.yml
/plugins/foo
/themes/bar
```

I'm using the same Dockerfile as you:

```
FROM docker.io/bitnami/redmine:4.1.0-debian-10-r25
RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev
WORKDIR /opt/bitnami/redmine/
COPY plugins/ /opt/bitnami/redmine/plugins
COPY themes/ /opt/bitnami/redmine/public/themes
RUN chown 1001:1001 . -R
#COPY ./redmine_issue_templates/* /opt/bitnami/redmine/redmine_issue_templates/
RUN bundle config unset deployment
RUN bundle install --no-deployment
```

Afterwards I built the docker image named `myredmine`, and deployed it with the below docker-compose file:

```yaml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      - 'mariadb_data:/bitnami'
  redmine:
    image: 'myredmine:latest'
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

The initialization worked without issues for me. And when I navigate to /opt/bitnami/redmine/plugins and /opt/bitnami/redmine/public/themes, the files were both there, and no errors were shown.

Could you let us know if we're missing anything?
