### ISSUE TITLE
Bitnami Redmine 4.1.1 + Sidekiq not working when run with command in docker-compose

### ISSUE THREAD

**Issue by contentadore** [bitnami/bitnami-docker-redmine#160]
**Description**

I installed a plugin, gems, tried to run Sidekiq in Redmine docker using the command in docker-compose.yml and got errors.

Questions:
1. How do I fix problems launching sidekiq?
2. Maybe this is the wrong way. Is there any other better way to run Redmine with Sidekiq in Docker?

**Steps to reproduce the issue:**

1. Create Dockerfile

```
FROM bitnami/redmine:4.1.1

RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev 
WORKDIR /opt/bitnami/redmine/
COPY redmine-plugins/redmine_keywords/ /opt/bitnami/redmine/plugins/redmine_keywords 
RUN bundle config unset deployment && bundle install --no-deployment
COPY database.yml /opt/bitnami/redmine/config/
```

2. Create docker-compose.yml

```
version: '3.8'
services:
   postgres:
     image: postgres:13
     volumes:
       - ./postgresql-data:/var/lib/postgresql/data
     environment:
       POSTGRES_USER: "user"
       POSTGRES_PASSWORD: "pass"
       POSTGRES_DB: "database"
     restart: always
   sidekiq:
     build:
       context: .
     image: redmine:sidekiq
     command: /bin/bash -lc '/opt/bitnami/ruby/bin/bundle exec sidekiq -e production'
     ports:
       - 80:3000
 environment:
       REDMINE_DB_POSTGRES: postgres
       REDMINE_DB_USERNAME: "user"
       REDMINE_DB_PASSWORD: "pass"
       REDMINE_DB_NAME: "database"
       REDMINE_SECRET_KEY_BASE: "..."
       # SECRET_KEY_BASE: "..."
       REDIS_URL: "redis://redis:6379/12"
       # DATABASE_URL: "postgres://user:pass@database"
     restart: always
     depends_on:
       - redis
       - postgres
   redis:
     image: redis
 volumes:
       - redis-data:/var/lib/redis/data
     restart: always
volumes:
   redis-data:
```

3. Start command:
`sudo docker-compose up --build`

**Describe the results you received:**

I have errors when "docker-compose up" starts:
```
production_redmine_1 | bundler: command not found: sidekiq
production_redmine_1 | Install missing gem executables with `bundle install`
```

**Describe the results you expected:**

Sidekiq starts successfully automatically when "docker-compose up" starts.

**Additional information you deem important (e.g. issue happens only occasionally):**

Sidekiq starts successfully  when  I enter to container
`docker exec -it <id container> bash`
and execute 
`bundle exec sidekiq`

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 12
  Running: 0
  Paused: 0
  Stopped: 12
 Images: 72
 Server Version: 20.10.2
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.3.9
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
Architecture: x86_64
 CPUs: 40
 Total Memory: 4GiB
 Name: vps8776777
 ID: NRN7:7G7J:5AO7:5J3O:ARF6:BOAM:SVOM:3PI3:ZUMX:5GFA:BATE:E7IE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/ 
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Plugin redmine_keywords isn't public. It contains gem "sidekiq" in Gemfile.
So we can use any plugin with Sidekiq.
