### ISSUE TITLE
Redmine not starting with error:  /opt/bitnami/scripts/libredmine.sh: line 324: 2: missing database port

### ISSUE THREAD

**Issue by rosch100** [bitnami/bitnami-docker-redmine#169]
**Description**

After the upgrade to the version "latest", redmine is not starting anymore. The logfile shows the following output:
```
redmine 11:11:28.63 
redmine 11:11:28.64 Welcome to the Bitnami redmine container
redmine 11:11:28.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine 11:11:28.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine 11:11:28.65 
redmine 11:11:28.68 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine 11:11:28.70 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine 11:11:28.80 INFO  ==> Restoring persisted Redmine installation
redmine 11:11:28.86 INFO  ==> Trying to connect to the database server
/opt/bitnami/scripts/libredmine.sh: line 324: 2: missing database port
```

**Steps to reproduce the issue:**

1. Upgrade a working redmine version to current
2. run the docker image

**Describe the results you received:**

redmine stops with the error (see above)

**Describe the results you expected:**

redmine starts and runs

**Additional information you deem important (e.g. issue happens only occasionally):**
- mariadb docker-compose.yml
```
version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_USER=MyUser
      - MARIADB_ROOT_PASSWORD=MyPassword
      - BITNAMI_DEBUG=true
    volumes:
      - /srv/DockerVolumes/sql:/bitnami
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  default:
    external:
      name: nginx-proxy
```
- redmine docker-compose.yml
```
version: '3'
services:
  redmine:
    image: 'bitnami/redmine:latest'
          #    image: 'bitnami/redmine:3.4.7'
    container_name: redmine
    restart: unless-stopped
    volumes:
      - '/srv/www/redmine:/bitnami'
      - '/srv/git:/bitnami/repos'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - REDMINE_LANGUAGE=de
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_DATABASE_USERNAME=MyUser
      - REDMINE_DATABASE_PASSWORD=MyPassword
      - REDMINE_DATABASE_MYSQL=mariadb
      - REDMINE_DATABASE_TYPE=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
    dns:
      - 1.1.1.1
networks:
  default:
    external:
      name: nginx-proxy
```

I downgraded to version 4.2.0 by changing in docker-compose.yml to:
   ` image: 'bitnami/redmine:4.2.0'`
Now, redmine is working fine again.
**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.16.5
 Git commit:        99e3ed8
 Built:             Tue Jun 15 03:13:20 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.16.5
  Git commit:       99e3ed8
  Built:            Tue Jun 15 03:14:07 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        %{CONTAINERD_GITCOMMIT}
 runc:
  Version:          1.0.0-rc93
  GitCommit:        14faf1c20948688a48edb9b41367ab07ac11ca91
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 10
  Paused: 0
  Stopped: 3
 Images: 13
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: %{CONTAINERD_GITCOMMIT}
 runc version: 14faf1c20948688a48edb9b41367ab07ac11ca91
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.10.46-1.ph4-esx
 Operating System: VMware Photon OS/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 948MiB
 Name: localhost
 ID: 2JKQ:YD6I:TKUW:HN63:LTEC:GQ7O:P4VK:G27U:SOPV:73AR:WOIY:NJGL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by migruiz4** [comment]
Hi @rosch100 ,

I haven't been able to reproduce the exact same issue, but we recently made some changes to the `bitnami/redmine` image and I have noticed your docker-compose includes some deprecated environment variables.

Could you please try using the following?
```diff
version: '3'
services:
  redmine:
    image: 'bitnami/redmine:latest'
          #    image: 'bitnami/redmine:3.4.7'
    container_name: redmine
    restart: unless-stopped
    volumes:
      - '/srv/www/redmine:/bitnami'
      - '/srv/git:/bitnami/repos'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - REDMINE_LANGUAGE=de
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_NAME=bitnami_redmine
-     - REDMINE_DATABASE_USERNAME=MyUser
+     - REDMINE_DATABASE_USER=MyUser
      - REDMINE_DATABASE_PASSWORD=MyPassword
-     - REDMINE_DATABASE_MYSQL=mariadb
      - REDMINE_DATABASE_TYPE=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
    dns:
      - 1.1.1.1
networks:
  default:
    external:
      name: nginx-proxy
```

Maybe the missing `REDMINE_DATABASE_USER` was causing the error.

**Comment by rosch100** [comment]
I changed docker-compose according to your suggestions. However, the error is the same when using image: `'bitnami/redmine:latest'`
Reverted to `image: 'bitnami/redmine:4.2.0'` and everything works again.

**Comment by migruiz4** [comment]
I looked into this issue, and the error is caused by the following code:

https://github.com/bitnami/bitnami-docker-redmine/blob/96f315e35ffcd6a7deac0c73650a2257f2b9de1e/4/debian-10/rootfs/opt/bitnami/scripts/libredmine.sh#L223-L233

`db_port="$(redmine_db_conf_get "${REDMINE_ENV}.port")" ` is not working.

Could you please share the content of your Redmine `database.yaml`? That would help us troubleshoot this issue and fix it for other users upgrading their Redmine.

In my case, it looks like this:
```console
root@bd9a89681825:/$ cat /opt/bitnami/redmine/config/database.yml 
# Default setup is given for MySQL 5.7.7 or later.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

production:
  adapter: mysql2
  database: bitnami_redmine
  host: mariadb
  username: MyUser
  password: MyPassword
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
  port: "3306"

...
```

**Comment by rosch100** [comment]
@migruiz4 it seems that the mandatory configuration of the port was added later in your code. In my config, the port setup is missing:
```
production:
  adapter: mysql2
  database: redmine
  host: mariadb
  username: MyUser
  password: MyPassword
  encoding: utf8mb4
```
If you change the code to assume the default port if no port is given, then it should work again.
