### ISSUE TITLE
SMTP mail settings bug

### ISSUE THREAD

**Issue by haobaozhong** [bitnami/bitnami-docker-redmine#172]
I set REDMINE_SMTP_HOST/PORT correctly, but redmine container's configuration file has nothing
I use https://bitnami.com/stack/redmine/helm

**Comment by alvneiayu** [comment]
hi @haobaozhong 

Setting up the variables with these values:
```
      - REDMINE_SMTP_HOST=localhost
      - REDMINE_SMTP_PORT_NUMBER=5555
```

I can not reproduce your problem:
```
File content: /opt/bitnami/redmine/config/configuration.yml

# default configuration options for all environments
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: "5555"
      authentication: login
      user_name: ""
      password: ""
      domain: ""
      enable_starttls_auto: "false"
```

Could you verify in your logs that you are seeing a log message like "Configuring SMTP credentials"? 

Thanks a lot

Álvaro

**Comment by corain35** [comment]
Hi
I have the same problem (Docker image 'bitnami/redmine: 4')

I have defined the following variables (in docker-compose.yml):
REDMINE_SMTP_HOST
REDMINE_SMTP_PORT
REDMINE_SMTP_USER
REDMINE_SMTP_PASSWORD

But Redmine tells me that the SMTP server is not configured in "config/configuration.yml" and indeed this file does not contain my SMTP config
No log message like "Configuring SMTP credentials" in docker logs

I had to set the SMTP values by editing the configuration.yml file and so they were accepted

Finally the REDMINE_EMAIL variable (set in docker-compose.yml) doesn't seem to work too. Redmine shows send address "redmine@example.net" and not my configured variable (and ReadMe says defaut to user@example.com)

**Comment by alvneiayu** [comment]
hi @corain35 

I can not reproduce your problem, maybe I am missing something. Could you share with me your docker-compose, please?

Docker compose used:
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_PASSWORD=testing
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
      - MARIADB_ROOT_PASSWORD=testing
  redmine:
    image: docker.io/bitnami/redmine:4
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_DATABASE_PASSWORD=testing
      - REDMINE_SMTP_HOST=localhost
      - REDMINE_SMTP_PORT_NUMBER=5555
      - REDMINE_SMTP_USER=helloworld
      - REDMINE_SMTP_PASSWORD=testing
      - REDMINE_EMAIL=helloworld@testing.com
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

Configuration in /opt/binami/redmine/config/configuration.yml
```
# default configuration options for all environments
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: "5555"
      authentication: login
      user_name: helloworld
      password: testing
      domain: helloworld
      enable_starttls_auto: "false"
```
Admin email setting up REDMINE_EMAIL:
```
MariaDB [bitnami_redmine]> SELECT * FROM email_addresses;
+----+---------+------------------------+------------+--------+---------------------+---------------------+
| id | user_id | address                | is_default | notify | created_on          | updated_on          |
+----+---------+------------------------+------------+--------+---------------------+---------------------+
|  1 |       1 | helloworld@testing.com |          1 |      1 | 2021-09-29 06:42:18 | 2021-09-29 06:42:18 |
+----+---------+------------------------+------------+--------+---------------------+---------------------+
1 row in set (0.000 sec)
```

Thanks a lot

Álvaro
