### ISSUE TITLE
Unable to turn off "enable_starttls_auto" from the environment variable

### ISSUE THREAD

**Issue by suzuki764** [bitnami/bitnami-docker-redmine#175]
**Description**

I need to turn off "enable_starttls_auto" for the convenience of the smtp server.
However, I cannot turn off "enable_starttls_auto" from the environment variable.

**Steps to reproduce the issue:**

1. Run the container using docker-compose.yml like the following.
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
  redmine:
    image: docker.io/bitnami/redmine:4
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_SMTP_HOST=*****
      - REDMINE_SMTP_PORT=587
      - REDMINE_SMTP_USER=*****
      - REDMINE_SMTP_PASSWORD=*****
      - REDMINE_SMTP_PROTOCOL=ssl
      - REDMINE_SMTP_AUTH=plain
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local

```

**Describe the results you received:**

When I sent the test email, I got the error "hostname does not match the server certificate".

**Describe the results you expected:**

The email is sent normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

I went inside the container and edited `bitnami/redmine/config/configuration.yml` from 
```
enable_starttls_auto: "false"
```
to
```
enable_starttls_auto: false
```
email was sent normally.

Is it a bug that `enable_starttls_auto: "false"` is set?

Thanks for the help.

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:10 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 39
  Running: 20
  Paused: 0
  Stopped: 19
 Images: 20
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: BLS6:Z7VT:2XY4:TLF2:6O3N:IB6U:DTOO:WIEZ:3CEY:AVUS:FNMB:KYNR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.1.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
