### ISSUE TITLE
Installing any plugin causes restart loop

### ISSUE THREAD

**Issue by KrisTheGreat** [bitnami/bitnami-docker-redmine#177]
I was trying to install some plugins in redmine. Unfortunately everytime I try to do so the redmine container got a restart loop. Currently I'm trying to install this plugin: https://github.com/southbridgeio/redmine_2fa/ but the problem occours with all I've tried. I install plugins by simply cloning repository into **plugins** directory and then restart the redmine container.

Environment:
```

  Redmine version                4.2.3.stable
  Ruby version                   2.6.9-p207 (2021-11-24) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp`
```
 I'm using docker-compose:

```
version: '3.1'

services:

 mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=Yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_PASSWORD=password
    volumes:
      - '/mnt/docker/redmine-mariadb:/bitnami'
 redmine:
    image: 'bitnami/redmine:latest'
    restart: always

    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
      - REDMINE_DB_PASSWORD=password
      - SMTP_HOST=host
      - SMTP_PORT=587
      - SMTP_USER=email
      - SMTP_PASSWORD=password
      - REDMINE_PLUGINS_MIGRATE=1

    volumes:
      - '/mnt/docker/redmine:/bitnami'
      - '/usr/scrips_redmine:/usr/scripts'

    ports:
      - 127.0.0.1:4000:3000


    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local

```

Log:
```
Attaching to docker_mariadb_1, docker_redmine_1
mariadb_1  | mariadb 16:42:18.24
mariadb_1  | mariadb 16:42:18.24 Welcome to the Bitnami mariadb container
mariadb_1  | mariadb 16:42:18.24 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | mariadb 16:42:18.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | mariadb 16:42:18.25 Send us your feedback at containers@bitnami.com
mariadb_1  | mariadb 16:42:18.25
mariadb_1  | mariadb 16:42:18.25 INFO  ==> ** Starting MariaDB setup **
mariadb_1  | mariadb 16:42:18.36 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1  | mariadb 16:42:18.36 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=Yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb 16:42:18.36 INFO  ==> Initializing mariadb database
mariadb_1  | mariadb 16:42:18.41 INFO  ==> Using persisted data
mariadb_1  | mariadb 16:42:18.44 INFO  ==> Running mysql_upgrade
mariadb_1  | mariadb 16:42:18.45 INFO  ==> Starting mariadb in background
redmine_1  | redmine 16:42:18.99
redmine_1  | redmine 16:42:18.99 Welcome to the Bitnami redmine container
redmine_1  | redmine 16:42:19.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | redmine 16:42:19.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | redmine 16:42:19.00
redmine_1  | redmine 16:42:19.02 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
redmine_1  | redmine 16:42:19.03 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 16:42:19.09 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:19.15 INFO  ==> Trying to connect to the database server
mariadb_1  | mariadb 16:42:19.92 INFO  ==> Stopping mariadb
mariadb_1  |
mariadb_1  | mariadb 16:42:21.94 INFO  ==> ** MariaDB setup finished! **
mariadb_1  | mariadb 16:42:22.01 INFO  ==> ** Starting MariaDB **
mariadb_1  | 2021-12-09 16:42:22 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.3.20-MariaDB) starting as process 1 ...
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Using Linux native AIO
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Uses event mutexes
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Number of pools: 1
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Waiting for purge to start
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: 10.3.20 started; log sequence number 57160557; transaction id 161956
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
mariadb_1  | 2021-12-09 16:42:22 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1  | 2021-12-09 16:42:22 0 [Note] InnoDB: Buffer pool(s) load completed at 211209 16:42:22
mariadb_1  | 2021-12-09 16:42:22 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2021-12-09 16:42:22 0 [Warning] 'proxies_priv' entry '@% root@acd57895fa13' ignored in --skip-name-resolve mode.
mariadb_1  | 2021-12-09 16:42:22 0 [Note] Reading of all Master_info entries succeeded
mariadb_1  | 2021-12-09 16:42:22 0 [Note] Added new Master_info '' to hash table
mariadb_1  | 2021-12-09 16:42:22 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.3.20-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
redmine_1  | redmine 16:42:24.28 INFO  ==> Executing database migrations
redmine_1  | redmine 16:42:25.35 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:25.41 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:25.50 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:42:26.55 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:26.61 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:26.72 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:42:27.93 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 16:42:27.99 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:28.06 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:28.16 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:42:29.82 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:29.88 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:29.98 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:42:32.45 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:32.51 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:32.61 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:42:36.90 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
redmine_1  | redmine 16:42:36.95 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:37.02 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:37.12 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:42:44.45 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:44.51 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:44.62 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:42:58.33 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:42:58.39 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:42:58.48 INFO  ==> Executing database migrations
docker_redmine_1 exited with code 1
redmine_1  | redmine 16:43:25.20 INFO  ==> Restoring persisted Redmine installation
redmine_1  | redmine 16:43:25.26 INFO  ==> Trying to connect to the database server
redmine_1  | redmine 16:43:25.35 INFO  ==> Executing database migrations
```

Please help
