### ISSUE TITLE
Is there a way to upgrade a redmine docker image properly with plugins installed?

### ISSUE THREAD

**Issue by smbajo** [bitnami/bitnami-docker-redmine#179]
### Name and Version

bitnami/redmine:4.2.3

### What steps will reproduce the bug?

I have installed redmine 4.2.3 and all the redmine up plugins and I want to upgrade the bitname image to the latest available version, and I get an error. The objective is to upgrade debian's security patches and upgrades, not to upgrade redmine app. 

This is what I've done:

1. I've installed redmine using the original docker-compose file from Bitnami, but indicating the image concrete tag I want to use: 

```console
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-redmine/master/docker-compose.yml > docker-compose.yml
```
In this concrete example, it's the 4.2.3-debian-10-r90 release. 

2. Next, I've run ```docker-compose up -d ``` with a non-root user, and everything goes ok so far here
```console
$ docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED              STATUS          PORTS                                   NAMES
fc00f3d5fd97   bitnami/redmine:4.2.3-debian-10-r90   "/opt/bitnami/script…"   About a minute ago   Up 13 seconds   0.0.0.0:80->3000/tcp, :::80->3000/tcp   vagrant_data_redmine_1
005b8fdb380c   bitnami/mariadb:10.4 
```

3. Next, I've installed the agile plugin using this simple bash script: 

```bash
#!/bin/bash
CONTAINER_NAME="vagrant_data_redmine_1"
docker exec -i "$CONTAINER_NAME" bash <<EOF
cd /opt/bitnami/redmine 
# copy from volume to the correct container's directory
cp -ra /tmp_p/* plugins/
# set correct owner to files
chown -R redmine:root /opt/bitnami/redmine/plugins/redmine_agile
# install necessary additional packages
install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev
cd /opt/bitnami/redmine
gosu redmine bundle config unset deployment
gosu redmine bundle install
gosu redmine bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
EOF
```
4. next step, I've restarted with ```docker-compose restart``` and everything goes ok up to this point

5. Image update, following the instructions given by Bitnami :

```console
$ docker pull bitnami/redmine:latest
$ docker images -a
REPOSITORY        TAG                   IMAGE ID       CREATED        SIZE
bitnami/redmine   latest                c247a8c678b3   19 hours ago   661MB
bitnami/mariadb   10.4                  5300ebdc4ad1   20 hours ago   328MB
bitnami/redmine   4.2.3-debian-10-r90   aa7d99bf4a10   3 weeks ago    660MB
$ docker-compose stop redmine
Stopping vagrant_data_redmine_1 ... done
$ docker-compose rm -v redmine
Going to remove vagrant_data_redmine_1
Are you sure? [yN] y
Removing vagrant_data_redmine_1 ... done
$ docker volume ls
DRIVER    VOLUME NAME
local     vagrant_data_mariadb_data
local     vagrant_data_redmine_data
```

6. change the tag in ```docker-compose.yml``` to point to the latest version: 

```yaml
    image: docker.io/bitnami/redmine:latest
```

7.  start the container with the new image:

```
 docker-compose up -d
```

8. and *I got an error and the container refuses to start*

```
redmine_1  | redmine 09:22:25.90 INFO  ==> Executing database migrations
redmine_1  | redmine 09:22:25.90 DEBUG ==> Generating secret tokens
redmine_1  | bundler: failed to load command: rake (/opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/bin/rake)
redmine_1  | /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/definition.rb:397:in `ensure_equivalent_gemfile_and_lockfile': You are trying to install in deployment mode after changing (Bundler::ProductionError)
redmine_1  | your Gemfile. Run `bundle install` elsewhere and add the
redmine_1  | updated Gemfile.lock to version control.
redmine_1  | 
redmine_1  | If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze 
redmine_1  | by running `bundle config unset deployment`.
redmine_1  | 
redmine_1  | The dependencies in your gemfile changed
redmine_1  | 
redmine_1  | You have added to the Gemfile:
redmine_1  | * redmine_crm
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/runtime.rb:13:in `setup'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler.rb:151:in `setup'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/setup.rb:20:in `block in <top (required)>'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/ui/shell.rb:136:in `with_level'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/ui/shell.rb:88:in `silence'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/setup.rb:20:in `<top (required)>'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:56:in `require_relative'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:56:in `kernel_load'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
redmine_1  | 	from /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
redmine_1  | 	from /opt/bitnami/ruby/bin/bundle:25:in `load'
redmine_1  | 	from /opt/bitnami/ruby/bin/bundle:25:in `<main>'
vagrant_data_redmine_1 exited with code 1

```

### What is the expected behavior?

(see before)

### What do you see instead?

(see before)

### docker-compose.yml

This is the docker-compose.yml I`ve used
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
  redmine:
    image: docker.io/bitnami/redmine:latest
   # image: docker.io/bitnami/redmine:4.2.3-debian-10-r90
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
      - './redmine/plugins:/tmp_p/'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - BITNAMI_DEBUG=true

volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

### workarounds I've tested 

I've tested other things in order to try to circunvent the error: 

- test the same steps with a different plugin
- execute blunder commands inside the plugin installation script as root user 
- create a new image from this Dockerfile: 

```Dockerfile
FROM docker.io/bitnami/redmine:latest
RUN bundle config --global frozen 1
WORKDIR /opt/bitnami/redmine
RUN bundle config unset deployment
RUN bundle config
RUN RAILS_ENV=production bundle exec rake redmine:plugins:migrate
```

And all of them have failed also. Is there a way to upgrade a redmine docker image properly with plugins installed?
Thanks in advance
