### ISSUE TITLE
https

### ISSUE THREAD

**Issue by gitpythonkaka** [bitnami/bitnami-docker-redmine#30]
How to use Https in bitnami-docker-redmine?

**Comment by prydonius** [comment]
Hey @gitpythonkaka. You would typically need to configure an nginx/Apache server as a reverse proxy to the Redmine container, and use that as the SSL endpoint.

I'm looking into SSL configuration for [bitnami/apache](/bitnami/bitnami-docker-apache) and [bitnami/nginx](/bitnami/bitnami-docker-nginx), and will get back to you with more information.

**Comment by prydonius** [comment]
Hi @gitpythonkaka, we've added documentation on how you can configure SSL for [bitnami/apache](https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates) and [bitnami/nginx](https://github.com/bitnami/bitnami-docker-nginx#using-custom-ssl-certificates).

You can use a virtual host that acts as a reverse proxy to your Redmine container (see [Apache mod_proxy docs](http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#forwardreverse) or [nginx reverse proxy docs](https://www.nginx.com/resources/admin-guide/reverse-proxy/)).

Hope this helps - let me know if you have any issues setting this up.

**Comment by sameersbn** [comment]
@gitpythonkaka Did this resolved the issue?

**Comment by devkev16** [comment]
I have the redmine running using https, I use https://github.com/jwilder/nginx-proxy and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion together to achieve automatically generation of lets-encrypt certs (also for my redmine)

**Comment by arapulido** [comment]
I am closing this issue, as the original reporter didn't get back and another user confirmed this was working.

**Comment by Gaddea** [comment]
@devkev16 

> I have the redmine running using https, I use https://github.com/jwilder/nginx-proxy and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion together to achieve automatically generation of lets-encrypt certs (also for my redmine)

Can you possibly send your docker-compose or a description on how you fixed it? Tried to get it working the whole weekend so I would really appreciate some help!

**Comment by devkev16** [comment]
Hi @Gaddea,

sry for the late response, my compose files are as follows:

docker-compose.yml (Redmine):

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_USER=redmine
      - MARIADB_ROOT_PASSWORD=asdassdasdasda
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  redmine:
    image: 'bitnami/redmine:3'
    volumes:
      - './redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    labels:
      kompose.service.type: nodeport
    links:
      - mariadb
    environment:
      - VIRTUAL_HOST=tracker.asdf.de
      - LETSENCRYPT_HOST=tracker.asdf.de
      - LETSENCRYPT_EMAIL=webmaster@asdf.de
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=asdassdasdasda
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_HOST=mariadb
      - SMTP_HOST=s73.goserver.host
      - SMTP_PORT=465
      - SMTP_USER=web14p4
      - SMTP_PASSWORD=asdassdasdasda
      - SMTP_TLS=true
      - REDMINE_EMAIL=tracker@asdf.de
      - REDMINE_LANG=de
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=pma.asdf.de
      - VIRTUAL_HOST=pma.asdf.de
volumes:
  mariadb_data:
    driver: local
```

docker-compose.yml (Proxy+LE):

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/ssl:/etc/nginx/dhparam:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    networks:
     - redmine_default
     - default

  nginx-lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-lets-encrypt
    depends_on:
      - nginx-proxy
    environment:
     - DEBUG=true
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - default
      - redmine_default

volumes:
  certs:
  html:
  conf.d:
  vhost.d:

networks:
  gitlab_default:
    external: true
  redmine_default:
    external: true
  default:
    internal: false
```

One thing is very important: You have to make sure that the proxy and the LE container are in the same network as the application you want to proxy and generate certificates for.
