### ISSUE TITLE
Database name

### ISSUE THREAD

**Issue by ebartlomiej89** [bitnami/bitnami-docker-redmine#51]
Hi.

I need to install Redmine with external mysql database. Please add support to set a database name in variable.

Best Regards
Bartłomiej Ekiert

**Comment by prydonius** [comment]
Hey @ebartlomiej89, thanks for opening the issue. We're currently working on adding this support to all of our apps, and will update this issue once we release a Redmine version with this feature.

Sorry for the delay.

**Comment by younoobtoo** [comment]
@beltran-rubo 
I'm trying to access an external database and for that purpose I want to specify an existing database. Could you tell me how you implemented this feature respectively how I can define a custom database? I couldn't find it in the commits of this project neither I found it in the redmine-xxx package. 

Thanks in advance and greets
Younoobtoo

**Comment by juan131** [comment]
Hi @younoobtoo 

We already support this feature. In order to point you to the right instructions, please let me know what you're interested at:

 - You already have a database created on your PostgreSQL server (not populated) and you want Redmine to use that database (providing the host, database name, user and password to connect to that database)
 - You have a PostgreSQL server with no databases created. You want Redmine to create its own database and populate it by providing "root" access to that PostgreSQL server.

**Comment by younoobtoo** [comment]
Hey @juan131, thanks for the fast response. 
What I'm trying to do is to connect my redmine pod to an already existing external mysql database. In this case I'm interested at the first option you mentioned in your comment but with a mysql database. 

Here also some background informations: I'm at this point where the connection on the mysql application is established but the user can't connect to the database itself, because I can't define my prefered database anywhere (like for example the other database options, which I define over environment variables). 

Greets, younoobtoo

**Comment by juan131** [comment]
Hi @younoobtoo 

In that case, you'd need to use a **docker-compose.yaml** such as the one below:

```
version: '2'
services:
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami'
    environment:
      - REDMINE_DB_MYSQL: YOUR_DATABASE_DOMAIN # To be replaced with actual value
      - REDMINE_DB_PORT_NUMBER: 3306 # Or any other you configured
      - REDMINE_DB_USERNAME: root # Or the equivalent MySQL admin user
      - REDMINE_DB_PASSWORD: PASSWORD # to be replaces with admin password
volumes:
  redmine_data:
    driver: local
```

**Comment by danielkucera** [comment]
I'm trying to set database name but the app keeps suffixing some random string. This is what I run:

```docker run -d -p 8087:3000 -e REDMINE_DB_USERNAME=redmine -e REDMINE_DB_DATABASE=bitnami_redmine -e REDMINE_DB_PASSWORD="dkmjfvndjafv" -e REDMINE_DB_MYSQL=1.1.1.1 bitnami/redmine```

and this is the result:
```

Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Configuring Redmine database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at 185.98.208.20:3306
mysql-c INFO  MySQL server listening and working at 185.98.208.20:3306
Error executing 'postInstallation': MySQL command failed to run. Error: 
 ERROR 1044 (42000) at line 1: Access denied for user 'redmine'@'%' to database 'bitnami_redmine_DTkVY'
```

**Comment by juan131** [comment]
Hi @danielkucera  

Could you try using the docker-compose below?

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=my-password
    volumes:
      - 'mariadb_data:/bitnami'
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_PORT_NUMBER=3306
      - REDMINE_DB_PASSWORD=my-password
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

**Comment by danielkucera** [comment]
@juan131 I don't want to use DB inside docker, I want to use a database on separate DB server.

**Comment by juan131** [comment]
Hi @danielkucera 

Sorry for the confusion in previous responses I did. After reviewing the code it seems that you should provide the 'root' credentials of your separate DB server to Redmine. 

When you run the command:

```
docker run -d -e REDMINE_DB_USERNAME=XXXX -e REDMINE_DB_PASSWORD=YYYY -e REDMINE_DB_MYSQL=1.1.1.1 bitnami/redmine
```

**XXXX** and **YYYY** must be replaced with the "root" credentials (user and password, respectively) of your database.

**Comment by danielkucera** [comment]
Hi @juan131 ,

I have no intention to provide it with root access to my db. I have created an separate user `redmine` with access to DB name `bitnami_redmine` and I want it to use exactly this database.

**Comment by juan131** [comment]
Hi @danielkucera 

That configuration is not supported on this Docker image yet. It'll assume the credentials you share are the 'root' ones and it'll try to create a new database using them.

It's something we support on other Docker Images such as WordPress or Drupal, therefore, the confusion.

**Comment by danielkucera** [comment]
@juan131 , thank you for the information. On the other hand, it is possible with the original docker image https://hub.docker.com/_/redmine/

**Comment by juan131** [comment]
Hi @danielkucera 

> it is possible with the original docker image

Do you mean the one maintained by the Docker team, don't you? 
Please note there are no "original" or "official" images in the Docker environment but different solutions provided by different people. Each of them with its pros and cons.

I agree that using external databases (which are already created) it's something we should support on this Docker Image and it's in our roadmap to include it on future versions of Redmine.

**Comment by ramonchu** [comment]
I see that the database name is something like 'bitnami_redmine_DTkVY'. It's created dynamically?  Why is not possible to set the database name as environment variable? It makes impossible to connect redmine with external database.

**Comment by juan131** [comment]
Hi @ramonchu 

As I mentioned before it's a feature which is not currently supported on this docker image. It's just related with the logic used to initialise Redmine since it assumes the database must be created.

@beltran-rubo I think it's worth to support this feature on Redmine since there are several users requesting it. Could we increase the priority to implement it?

**Comment by zx1986** [comment]
It's 2019.
The kubernetes helm chart stable/redmine which using Bitnami Redmine can NOT specify custom database name still :-(

**Comment by juan131** [comment]
Hi @zx1986 

You're right and we should revisit our priorities so we can work on this feature which has been requested for quite a long time. We'll try to do release a new container with this feature within the next two weeks.

**Comment by alemorcuq** [comment]
Hi, @danielkucera, @ramonchu, @zx1986, @ebartlomiej89, @younoobtoo.

We have released a new version of the container that support external databases. The example `docker-compose.yml` file uses a database created by the `mariadb` container to setup `redmine`:

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      - 'mariadb_data:/bitnami'
  redmine:
    image: 'bitnami/redmine:4'
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

Please, try it and let us know how it goes.

Regards,
Alejandro
