### ISSUE TITLE
Cannot boot image: cannot load such file -- vpim

### ISSUE THREAD

**Issue by anoduck** [bitnami/bitnami-docker-redmine#68]
During attempted installation, received error and docker image immediately exited. 

```
Error executing 'postInstallation': rake aborted!
redmine_1  | LoadError: cannot load such file -- vpim
```

Was using docker-compose for the installation. Image will not even start without exiting early with the above error.

**Comment by juan131** [comment]
@anoduck can you share with us the docker-compose.yml file you're using? I just tried `docker-compose up` using the latest version of the image: 3.3.2-r0 and I did not find any issue.

**Comment by anoduck** [comment]
Whoa...that is weird. Sure thing...

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '10084:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

I have been working on it. But, I have not fetched the newest changes which occurred six days ago. 
My bad.
Which having not done this, might be the cause of the error code I am experiencing. Regardless, this error occurred after running the container for the second time. It would load up originally, I would begin configuration, and then when I went to reboot the image the error would raise it's head.

I have cloned the new changes in a repository, and ran the docker-compose file. It is currently downloading the images needed. It should finish up shortly, at which time I shall begin to see if the error appears again.

I am starting to believe that either, the bug was fixed with the newest update, or this bug is related to a plugin installed. If either case proves to show signs of validity, I think our job here will be done and will close out the ticket. 

Thanks so much for the response, and any help that can be given. Have a great day.
