### ISSUE TITLE
Can't set up git repository

### ISSUE THREAD

**Issue by Pilli** [bitnami/bitnami-docker-redmine#93]
Hi.

**Description**

I'm trying to set up a Git repository but I can't get it, I get this error message: "SCM command is not available. Please check settings on the administration panel."

![1](https://user-images.githubusercontent.com/326305/28478040-f48dc83e-6e56-11e7-9e03-3fb29f9cd655.png)

I've also tried to enable git SCM in *Administration -> Settings -> Repositories* but all SCM commands are invalid:

![2](https://user-images.githubusercontent.com/326305/28478655-a390f25a-6e59-11e7-9543-003bc9a2d077.png)

Then I've configured git command in *config/configuration.yml* and I've restarted the container after do it, but the command is invalid too:

![3](https://user-images.githubusercontent.com/326305/28478887-7a856a20-6e5a-11e7-87ad-c93452d96f2b.png)

My docker.compose.yml is:
```yaml
version: '2'

networks:
  app-tier:
    driver: bridge

services:

  mariadb:
    image: 'bitnami/mariadb:10.1.25-r0'
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=a1
    volumes:
      - '/var/lib/mariadb:/bitnami'
    networks:
      - app-tier

  phpmyadmin:
    image: 'bitnami/phpmyadmin:4.7.3-r0'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
    depends_on:
      - mariadb
    volumes:
      - '/var/lib/phpmyadmin:/bitnami'
    networks:
      - app-tier

  redmine:
    image: 'bitnami/redmine:3.4.2-r0'
    ports:
      - '3000:3000'
    environment:
      - REDMINE_USERNAME=admin
      - REDMINE_PASSWORD=a1
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_USERNAME=root
      - REDMINE_DB_PASSWORD=a1
    depends_on:
      - mariadb
    volumes:
      - '/var/lib/redmine:/bitnami'
    networks:
      - app-tier
```

How can I enable git repositories?

**Steps to reproduce the issue:**

1. Run `docker-compose up -d`
2. Create a new project in Redmine
3. Set up a repository for the new project.

**Describe the results you received:**

I can't set up the repository

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:16:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-3-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 3.863GiB
Name: docker-debian
ID: XAOG:BIWT:TF73:CAM6:3QKR:L3YY:URZS:6QLB:F2LV:NTS2:6SUJ:OAFD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker is running in a VirtualBox Machine with Debian strech.
- Output of `lsb_release -a`
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.0 (stretch)
Release:        9.0
Codename:       stretch
```

Git is installed in container. 
- Output of `sudo docker exec -it redmine git version `

```
git version 2.14.0-rc0
```

**Comment by jotadrilo** [comment]
Hi @Pilli,

First of all, thanks for your detailed instructions.

Thanks to them we realized that we included a Release Candidate version of Git in our images and we downgraded it accordingly. That version introduces some backward incompatibilities so Redmine fails to perform some validation actions:

```
redmine_1     | App 192 stderr: error: unknown option `no-color'
redmine_1     | App 192 stderr: usage: git version [<options>]
redmine_1     | App 192 stderr:
redmine_1     | App 192 stderr:     --build-options       also print build options
```

If you modify your `docker-compose.yml` file to pull from `bitnami/redmine:3.4.2-r1` instead, you should get rid of this issue. I tested your setup and it worked fine.

I hope it helps!

- - - - - - - - - - - - -
Was my answer helpful? Click on :heart:

**Comment by Pilli** [comment]
Hi @jotadrilo,

I'm trying your new version and now I'm able to set up a git repository. Thanks for the update.
Before your comment I've fixed it modifying my `docker-compose.yml` and installing git-core and mercurial in the `bitnami/redmine` image, I need mercurial too.

My "new" docker-compose.yml was:
```
version: '2'

networks:
  app-tier:
    driver: bridge

services:

  mariadb:
    image: 'bitnami/mariadb:10.1.25-r0'
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=a1
    volumes:
      - '/var/lib/mariadb:/bitnami'
    networks:
      - app-tier

  phpmyadmin:
    image: 'bitnami/phpmyadmin:4.7.3-r0'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
    depends_on:
      - mariadb
    volumes:
      - '/var/lib/phpmyadmin:/bitnami'
    networks:
      - app-tier

  redmine:
    build:
        context: ./
    ports:
      - '3000:3000'
    environment:
      - REDMINE_USERNAME=admin
      - REDMINE_PASSWORD=a1
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_USERNAME=root
      - REDMINE_DB_PASSWORD=a1
    depends_on:
      - mariadb
    volumes:
      - '/var/lib/redmine:/bitnami'
    networks:
      - app-tier
```
And my Dockerfile was:

```
FROM bitnami/redmine

RUN install_packages git-core mercurial
RUN rm -rf /opt/bitnami/git

EXPOSE 3000
```
I forgot to comment my fix. :(
Can you also install mercurial in your next image?
I think this issue can be closed.

Thanks and best regards.
